#:schema node_modules/wrangler/config-schema.json
name = "scheduled"
main = "src/index.ts"
compatibility_date = "2025-09-15"
minify = true
upload_source_maps = true
workers_dev = false

[observability]
enabled = true
traces.enabled = true

[triggers]
crons = ["0 0 * * *"]
